import Image from 'next/image';
import { Inter } from 'next/font/google';
import Header from "../components/Header";
import Banner from '@/components/Banner';
import Head from 'next/head';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <Head className="">
      <title>KKairbnb</title>
      <meta name='description' content='Generated by create next app' />
          
        <link rel='icon' href='/kklogov4.jpg' />
        <meta name='viewport' content='width=device-width, initial-scale=1.0' />
      <Header/>
      <Banner/>
    </Head>
  )
}
